### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by az09** [Komzpa/osm-contacts#1]
Многие пункты могут быть не доступны напрямую, но при этом существуют выложенные в интернете в широкий доступ логи чатов. Для отражения такой ситуации предлагаю добавлять атрибут _logs_ или _log_url_.

**Comment by Komzpa** [comment]
done in #2

**Comment by az09** [comment]
вот и не done, логов может быть целый массив )) как быть?

**Comment by Komzpa** [comment]
add the entry point to start of it :)
